version: '3.8'

services:
  backend:
    build:
      context: ./connect  # Setzt den Kontext auf den connect-Ordner
      dockerfile: Dockerfile  # Hier ist der Dockerfile für Django
    ports:
      - "8000:8000"  
    command: daphne -b 0.0.0.0 -p 8002 connect.asgi:application  # Daphne auf Port 8002
    volumes:
      - ./connect:/app  # Synchronisiert den connect-Ordner
    env_file:
      - ./connect/.env  # Umgebungsvariablen (falls vorhanden)
    environment:  # Füge dies hinzu
      - DJANGO_SETTINGS_MODULE=connect.settings  


  frontend:
    build:
      context: ./frontend  # Setzt den Kontext auf den frontend-Ordner
      dockerfile: Dockerfile  # Hier ist der Dockerfile für React
    ports:
      - "3000:3000"  # Bindet Port 80 vom Container an Port 8080 des Hosts

  redis:
    image: "redis:alpine"  # Redis-Dienst
    ports:
      - "6380:6379"

networks:
  default:
    driver: bridge
