# Generated by Django 4.2.5 on 2024-10-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
