# Generated by Django 4.2.5 on 2024-09-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0003_channel_channelmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
