# Generated by Django 4.2.5 on 2024-09-12 14:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0007_alter_channelmembership_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='privatechat',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='message',
            name='private_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev.privatechat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dev.channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='privatechat',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_chat_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='privatechat',
            name='created_at',
        ),
    ]
