# Generated by Django 4.2.5 on 2024-09-12 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0008_alter_privatechat_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='private_chat',
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='dev.channel'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='PrivateChat',
        ),
    ]
