# Generated by Django 4.2.5 on 2024-09-13 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0009_remove_message_private_chat_alter_message_channel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
