# Generated by Django 4.2.5 on 2024-09-16 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0011_reaction'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev.message'),
        ),
        migrations.AlterField(
            model_name='reaction',
            name='reaction_type',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('user', 'message', 'reaction_type')},
        ),
        migrations.RemoveField(
            model_name='reaction',
            name='emoji',
        ),
    ]
