# Generated by Django 4.2.5 on 2024-09-19 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0013_thread'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThreadReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction_type', models.CharField(max_length=255)),
                ('thread_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dev.thread')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'thread_message', 'reaction_type')},
            },
        ),
    ]
