# Generated by Django 4.2.5 on 2024-09-19 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0015_message_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='file',
            new_name='file_url',
        ),
    ]
