# Generated by Django 4.2.5 on 2024-09-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0017_thread_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
