# Generated by Django 4.2.5 on 2024-09-19 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0018_alter_thread_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='file_url',
            field=models.FileField(blank=True, null=True, upload_to='threads/'),
        ),
    ]
