# Generated by Django 4.2.5 on 2024-09-20 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0020_alter_thread_file_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='file_url',
            new_name='file',
        ),
    ]
