# Generated by Django 4.2.5 on 2024-09-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0021_rename_file_url_thread_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='file',
            new_name='file_url',
        ),
    ]
