# Generated by Django 4.2.5 on 2024-09-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev', '0023_alter_thread_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
